[[api-react-components-results-per-page]]
= ResultsPerPage

// :keywords: demo

Shows a dropdown for selecting the number of results to show per page.

Uses [20, 40, 60] as default options. You can use `options` prop to pass custom options.

**Note:** When passing custom options make sure one of the option values match
the current `resultsPerPageProp` value, which is 20 by default.
To override `resultsPerPage` default value, use the <<api-react-search-provider-initial-state,initial state>> property.

[discrete]
[[api-react-components-results-per-page-example]]
== Example

[source,jsx]
----

import { ResultsPerPage } from "@elastic/react-search-ui";

...

<ResultsPerPage />
----

[discrete]
[[api-react-components-results-per-page-example-using-custom-options]]
== Example using custom options

[source,jsx]
----

import { SearchProvider, ResultsPerPage } from "@elastic/react-search-ui";

<SearchProvider
    config={
        ...
        initialState: {
            resultsPerPage: 5
        }
    }
>
    <ResultsPerPage options={[5, 10, 15]} />
</SearchProvider>
----

[discrete]
[[api-react-components-results-per-page-properties]]
== Properties

|===
| Name| Description

| className
|

| options
| Type: `number[]`. Dropdown options to select the number of results to show per page.

| view
| Used to override the default view for this Component. See <<api-react-components-results-per-page-view-customization,View customization>> below.

| *
| Any other property passed will be passed through and available to use in a Custom View.
|===

[discrete]
[[api-react-components-results-per-page-view-customization]]
== View customization

A complete guide to view customization can be found in the <<guides-customizing-styles-and-html-customizing-html,Customization: Component views and HTML>> section.

The following properties are available in the view:

|===
| Name| Description

| className
| Passed through from main component.

| onChange
| function(value: number) - Call this function with the select value from `options` after a user has made a selection.

| options
| Passed through from main component.

| value
| The currently selected option.
|===

See https://github.com/elastic/search-ui/blob/main/packages/react-search-ui-views/src/ResultsPerPage.tsx[ResultsPerPage.tsx] for an example.
