[[api-connectors-app-search]]
= App Search Connector

++++
<titleabbrev>Connectors API</titleabbrev>
++++

// :keywords: app search connector

.Deprecation Notice
[IMPORTANT]
====
App Search connector for Search UI is deprecated and will no longer be
supported. Please migrate to <<tutorials-elasticsearch,Elasticsearch Connector>>
for continued support.
====

This Connector is used to connect Search UI to Elastic's https://www.elastic.co/cloud/app-search-service[App Search] API.

[discrete]
[[api-connectors-app-search-usage]]
== Usage

[source,shell]
----
npm install --save @elastic/search-ui-app-search-connector
----

[source,js]
----
import AppSearchAPIConnector from "@elastic/search-ui-app-search-connector";

const connector = new AppSearchAPIConnector({
  searchKey: "search-371auk61r2bwqtdzocdgutmg",
  engineName: "search-ui-examples",
  endpointBase: "http://127.0.0.1:3002"
});
----

[discrete]
[[api-connectors-app-search-additional-options]]
=== Additional options

Additional options will be passed through to the underlying
https://github.com/elastic/app-search-javascript[APIclient]. Any valid parameter of the client can be used.

[source,js]
----
const connector = new AppSearchAPIConnector({
  searchKey: "search-371auk61r2bwqtdzocdgutmg",
  engineName: "search-ui-examples",
  endpointBase: "http://127.0.0.1:3002",
  cacheResponses: false
});
----

[discrete]
[[api-connectors-app-search-options]]
== Options

|===
| Param| Description

| searchKey
| Required. String. Credential found in your App Search Dashboard

| engineName
| Required. String. Engine to query, found in your App Search Dashboard

| endpointBase
| Required. String. Endpoint path, found in your App Search Dashboard

| cacheResponses
| Optional. Boolean. Default is true. By default, connector will keep an in browser memory result cache of previous requests.

| hostIdentifier
| Optional. Useful when proxying the Swiftype API or developing against a local API server.

| beforeSearchCall
| Optional. A hook to amend query options before the request is sent to the API in a query on an "onSearch" event.

| beforeAutocompleteResultsCall
| Optional. A hook to amend query options before the request is sent to the API in a "results" query on an "onAutocomplete" event.

| beforeAutocompleteSuggestionsCall
| Optional. A hook to amend query options before the request is sent to the API in a "suggestions" query on an "onAutocomplete" event.
|===
