[[overview]]
= Search UI

++++
<titleabbrev>What is Search UI?</titleabbrev>
++++

// :description: For the fast development of modern, engaging search experiences. 🎉
// :keywords: demo

A JavaScript library for the fast development of modern, engaging search experiences with https://www.elastic.co/[Elastic]. Get up and running quickly without re-inventing the wheel.

[discrete]
[[overview-features]]
== Features 👍

* **You know, for search** - Maintained by https://elastic.co[Elastic], the team behind Elasticsearch.
* **Speedy Implementation** - Build a complete search experience with a few lines of code.
* **Customizable** - Tune the components, markup, styles, and behaviors to your liking.
* **Smart URLs** - Searches, paging, filtering, and more, are captured in the URL for direct result linking.
* **Flexible front-end** - Not just for React. Use with any JavaScript library, even vanilla JavaScript.
* **Flexible back-end** - Use it with Elasticsearch, Elastic Enterprise Search, or any other search API.

[discrete]
[[overview-live-demos]]
== Live demos 👀

[discrete]
[[overview-connectors]]
=== Connectors

* https://codesandbox.io/s/github/elastic/search-ui/tree/main/examples/sandbox?from-embed=&initialpath=/elasticsearch&file=/src/pages/elasticsearch/index.js[Elasticsearch]
* https://codesandbox.io/s/github/elastic/search-ui/tree/main/examples/sandbox?from-embed=&initialpath=/site-search&file=/src/pages/site-search/index.js[Elastic Site Search (Swiftype)]
* ⚠️ DEPRECATED. https://codesandbox.io/s/github/elastic/search-ui/tree/main/examples/sandbox?from-embed=&initialpath=/app-search&file=/src/pages/app-search/index.js[Elastic App Search]
* ⚠️ DEPRECATED. https://codesandbox.io/s/github/elastic/search-ui/tree/main/examples/sandbox?from-embed=&initialpath=/workplace-search&file=/src/pages/workplace-search/index.js[Elastic Workplace Search]

[discrete]
[[overview-examples]]
=== Examples

* https://codesandbox.io/s/github/elastic/search-ui/tree/main/examples/sandbox?from-embed=&initialpath=/search-as-you-type&file=/src/pages/search-as-you-type/index.js[Search as you type]
* https://codesandbox.io/s/github/elastic/search-ui/tree/main/examples/sandbox?from-embed=&initialpath=/search-bar-in-header&file=/src/pages/search-bar-in-header/index.js[Search bar in header]
* https://codesandbox.io/s/github/elastic/search-ui/tree/main/examples/sandbox?from-embed=&initialpath=/customizing-styles-and-html&file=/src/pages/customizing-styles-and-html/index.js[Customizing Styles and Components]

[discrete]
[[overview-get-started]]
== Get Started 🌟

[discrete]
[[overview-installation]]
=== Installation

[source,sh]
----
npm install @elastic/search-ui @elastic/react-search-ui @elastic/react-search-ui-views
# or
yarn add @elastic/search-ui @elastic/react-search-ui @elastic/react-search-ui-views
----

[discrete]
[[overview-tutorials]]
=== Tutorials

Get started quickly with Search UI and your favorite Elastic product by following one of the tutorials below:

* <<tutorials-elasticsearch,Elasticsearch>>
* <<tutorials-app-search,Elastic App Search (⚠️ DEPRECATED)>>
* <<tutorials-workplace-search,Elastic Workplace Search (⚠️ DEPRECATED)>>

[discrete]
[[overview-use-cases]]
== Use Cases 🛠️

[discrete]
[[overview-ecommerce]]
=== Ecommerce

Search UI works great in the ecommerce use-case. Check out our <<solutions-ecommerce,ecommerce guide>> that includes demo and code examples, as well as general guidance for ecommerce search.

[discrete]
[[overview-faq]]
== FAQ 🔮

[discrete]
[[overview-is-search-ui-only-for-react]]
=== Is Search UI only for React?

Search UI is "headless". You can use vanilla JavaScript or write support for it into any JavaScript framework.

https://github.com/elastic/search-ui/tree/main/packages/search-ui[Read about the search-ui package] for more information, or check out the https://github.com/elastic/vue-search-ui-demo[Vue.js Example].

[discrete]
[[overview-can-i-use-my-own-styles]]
=== Can I use my own styles?

You can!

Read the <<guides-customizing-styles-and-html,Custom Styles and Layout Guide>> to learn more, or check out the https://github.com/elastic/seattle-indies-expo-search[Seattle Indies Expo Demo].

[discrete]
[[overview-can-i-build-my-own-components]]
=== Can I build my own Components?

Yes! Absolutely.

Check out the <<guides-creating-your-own-components,Build Your Own Component Guide>>.

[discrete]
[[overview-does-search-ui-only-work-with-app-search]]
=== Does Search UI only work with App Search?

Nope! We do have two first party connectors: Site Search and App Search.

But Search UI is headless. You can use _any_ Search API.

Read the <<guides-building-a-custom-connector>> to learn more about building your own connector for your API.

[discrete]
[[overview-how-do-i-use-this-with-elasticsearch]]
=== How do I use this with Elasticsearch?

Read the <<api-connectors-elasticsearch,Elasticsearch Connector>> docs.

[discrete]
[[overview-where-do-i-report-issues-with-the-search-ui]]
=== Where do I report issues with the Search UI?

If something is not working as expected, please open an https://github.com/elastic/search-ui/issues/new[issue].

[discrete]
[[overview-where-can-i-go-to-get-help]]
=== Where can I go to get help?

The Enterprise Search team at Elastic maintains this library and are happy to help. Try posting your question to the https://discuss.elastic.co/c/enterprise-search/84[Elastic Enterprise Search] discuss forums. Be sure to mention that you're using Search UI and also let us know what backend your using; whether it's App Search, Site Search, Elasticsearch, or something else entirely.

[discrete]
[[overview-contribute]]
== Contribute 🚀

We welcome contributors to the project. Before you begin, a couple notes...

* Read the https://github.com/elastic/search-ui/blob/main/CONTRIBUTING.md[Search UI Contributor's Guide].
* Prior to opening a pull request, please:
+
** Create an issue to https://github.com/elastic/search-ui/issues[discuss the scope of your proposal].
** Sign the https://www.elastic.co/contributor-agreement/[Contributor License Agreement]. We are not asking you to assign copyright to us, but to give us the right to distribute your code without restriction. We ask this of all contributors in order to assure our users of the origin and continuing existence of the code. You only need to sign the CLA once.
* Please write simple code and concise documentation, when appropriate.

[discrete]
[[overview-license]]
== License 📗

https://github.com/elastic/search-ui/blob/main/LICENSE.txt[Apache-2.0] © https://github.com/elastic[Elastic]

Thank you to all the https://github.com/elastic/search-ui/graphs/contributors[contributors]! 🙏 🙏
