name: Elastic Builder
on:
  pull_request_target:
    types: [closed, opened, synchronize, reopened]

jobs:
  preview:
    name: Builder, staging PR
    runs-on: ubuntu-latest
    steps:
      - name: Setup workspace
        uses: actions/checkout@v2

      - name: Checkout current branch into temp
        if: github.event.pull_request.merged == false
        uses: actions/checkout@v2
        with:
          path: 'temp'
          fetch-depth: 2
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Checkout current branch into temp
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v2
        with:
          path: 'temp'

      - name: Checkout essential repos
        uses: actions/checkout@v2
        with:
          repository: elastic/search-ui
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/search-ui

      - name: Show workspace
        shell: bash
        run: ls -lat ${{ github.workspace }}

      - name: Portal
        shell: bash
        run: |
          rsync --ignore-missing-args -zavpm ${{ github.workspace }}/temp/. ${{ github.workspace }}/search-ui/.
      - name: Generate preview
        if: github.event.pull_request.merged == false
        uses: elastic/builder@v21.3.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_SEARCH_UI}} #Required
          vercel-project-name: search-ui
          github-token: ${{ secrets.VERCEL_GITHUB_TOKEN }} #Optional
          working-directory: ./