on:
  pull_request_target:
    paths:
      # Change docs dir to your repos docs dir
      - "docs/**.mdx"
      - "docs/**.docnav.json"
      - "docs/**.docapi.json"
      - "docs/**.devdocs.json"
      - "docs/**.jpg"
      - "docs/**.jpeg"
      - "docs/**.svg"
      - "docs/**.png"
      - "docs/**.gif"
    types: [closed, opened, synchronize, labeled]

jobs:
  publish:
    if: contains(github.event.pull_request.labels.*.name, 'ci:doc-build')
    uses: elastic/workflows/.github/workflows/docs-versioned-publish.yml@main
    with:
      # Refers to Vercel project
      project-name: elastic-dot-co-docs-preview-docs
      # Which prebuild step (dev or not)
      prebuild: wordlake-docs
      # Docsmobile project dir
      site-repo: docs-site
    secrets:
      VERCEL_GITHUB_TOKEN: ${{ secrets.VERCEL_GITHUB_TOKEN_PUBLIC }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_PUBLIC }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_PUBLIC }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_ELASTIC_DOT_CO_DOCS_PRODUCTION_PUBLIC }}
